---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-trust-bundle-for-harbor
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDKTCCAhGgAwIBAgIRAPKAPh208e3DHDP7jZOrVVMwDQYJKoZIhvcNAQELBQAw
    FDESMBAGA1UEAxMJSGFyYm9yIENBMB4XDTI1MDcyOTIwMDc0OFoXDTM1MDcyNzIw
    MDc0OFowFDESMBAGA1UEAxMJSGFyYm9yIENBMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEAsEDfogO1gmHwreBBN/QSwWY59PTtf8JB8uiyZno2wZJ9zgiU
    ho+82rPsJakyruKqOZx7lSItJNjbqWHSJVHhA8aYvyHznGj7+QjoI50vGVLXUfgo
    CbzZxo4YHyzMzyLcNN0g8lLZBu/yJz4kypScFxFMAJK34BDmpZLaLd0W1mqTqAJg
    aGH3355LzGDxl5xuOZWATaRGTYlHeBTWBFjxfOR6qP4A9kPxL8PQFSXB0QSimjw0
    45Zxe8wqZyy6AmnrWz0T4WD4mXa7NmHwka3S7IC1OBC6VdPLUA6FytGrfbtmB+/4
    m9lH9ti+/+4DGSo7FcuzlnT6TYLhmGOEh3CjhQIDAQABo3YwdDAOBgNVHQ8BAf8E
    BAMCAgQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQF
    MAMBAf8wHQYDVR0OBBYEFFNyKm11+yQ9Qu9OGZoM9UJScJY4MBMGA1UdEQQMMAqC
    CGhhcmJvcmNhMA0GCSqGSIb3DQEBCwUAA4IBAQBf04kszDKMXF+MMz309tFs4/Gh
    1d0cCCmEBmdKmGIfH2EB1Y+pxIGMJgm2E0rt6F0QVOJI0rj4nkpBpki3gEI79Np6
    NZME7lo/65xos9xvI8mc4f3dKGorAk8006P9f1S8KZXHJBmhHm4UkQn33aQhP2A0
    ZlYz//3Dz4dDwbpjDuz0mUNFObBjj7JsjpHj0A8dCK3fP6+xYCDB62a2PgyZpjyG
    GXIx3z89qll9g0R4bBCji3pbKmcSjBpFrGltmFuo0HQAuHSKvhqIImt3kq7ZWfNV
    Q+Lj43uaXeDOVD6x/Bb6inEurWNRljzoOs3CxvDaEKU8CELvcRN3aU9QeUxR
    -----END CERTIFICATE-----
