---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-trust-bundle-for-harbor
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDKDCCAhCgAwIBAgIQXgWEkZxndHr9vb/WbZZalDANBgkqhkiG9w0BAQsFADAU
    MRIwEAYDVQQDEwlIYXJib3IgQ0EwHhcNMjYwMzA2MTYxMzE1WhcNMzYwMzAzMTYx
    MzE1WjAUMRIwEAYDVQQDEwlIYXJib3IgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQC8waeinVKBPcJAAoYDk/9hfthJ2ToGgjXVKe+nhmNnFu1r7+rZ
    se58GwKjfPJWRb4qf0QjO1Q905HaQL/B1x8SE3xeKXhAPlvdyzUqSyKF8FutxuX2
    SUvKQJ9FPlDGws9+8/tfWZDxHA9cHtuUuXdP9JQ9t8glAtWVgSrhS+h22wGvReSg
    YD39DHKaf+A37V7gD0kaWHqHoFmNc3oZV0r8tWf6vtRXWeiiKcoQf+u7xOoMd+Rr
    3T7dVrf8E6aljiCUrLD3SgXPv6XrOSW+ItHxHKoQGM9X8b3jLOWPbWllXqlysIPH
    UvxsmU4L/3u846x1ugRak85Xg3C/jkr+2AGdAgMBAAGjdjB0MA4GA1UdDwEB/wQE
    AwICBDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUw
    AwEB/zAdBgNVHQ4EFgQUI49K7zetblLaN94aP8ZnukBxdcUwEwYDVR0RBAwwCoII
    aGFyYm9yY2EwDQYJKoZIhvcNAQELBQADggEBALu4w1j0CvQ8dD63KT4+Tdr1Tf/k
    Juh1tejyWi1CaSiUihgFNSpF4BXQN+ojjxY1DL6XAYaCtiwmIaqqKowWuqVdm67F
    awn1Yp/kYw4SRFc2ZaUAs+Z2XxUjs4LMuCTcmx9ztEvUQW9RnGXPkKbrbkFMP5fC
    Z11jyj6EeCrevHrwfo/4eV94PAzS4EShEJlZZ4BbAWyVb5sonY5vVbanTFYHOJdK
    y0eE4duI8TNxB1EPmNi4t4uhEQ6YU7ngxyRBSMVzvBgtRAJz/ngkJTPYN1HvdQHY
    b8hlq06PngPl+VJFOxlpiiI0GA5YqaE7NVAEn/Wch49TL6Tgqp4aoGstI4s=
    -----END CERTIFICATE-----

