---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-trust-bundle-for-oidc
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFVjCCAz6gAwIBAgIUEz4X1QBz2NF466iGe+oyvvwTsxkwDQYJKoZIhvcNAQEL
    BQAwLDEPMA0GA1UECgwGZXEubGFiMRkwFwYDVQQDDBBhdXRoZW50aWsuZXEubGFi
    MB4XDTI2MDMxODE2MTcxMFoXDTI5MDYzMDE2MTcxMFowLDEPMA0GA1UECgwGZXEu
    bGFiMRkwFwYDVQQDDBBhdXRoZW50aWsuZXEubGFiMIICIjANBgkqhkiG9w0BAQEF
    AAOCAg8AMIICCgKCAgEAseTDX9FJuo7RdeMmMeRSCIRk6E2f4XjGkrVqUIhgTs13
    ZRu51jUWizSamxpEFemFh/4nVUl1ZtTekYqMwKFS7OZ2SjgqwwcJmo8yITryXCR1
    0qw4t9VMSDRRtLeWdKAWsDKp4x2dcpOLgabXIU1jGII8wzvQLdtw/UG5oFIYGETF
    iqDPi+lAgr01MQLJdc5B26kM5ZlcdflRea/piXrMzcEuYQoXMWCqgUhIXqcJ8Hb9
    KaEqY8YswekdLWWXQoFvNk1gXgkQ//1c50YwKXJEWsR+EcjRmB+j1oqltjgA0otJ
    DL+T2izIRL29Tal14/XNe6U9rDKmm8nWK7Bg9i1Fjg813o0NfvTV3sFUD7Ywru1h
    CxcqszhukBJEJFcJ8OhWNfsqc0NPBuZbBTHB+xS4+sBvVuGHdrbHm0DU/xMhhQw9
    n+/LdEYOF3k0Rs3TeiC+JbQtR2oyQn4cU+nH32VK8rAp4Xu5Y9ItKE4sKvtrS7Jb
    cbn/v6+Y5jf/TP98orA/uax3PDWXI78cMJjesWbnp7PXiqYmC9DZij8N+R9s1DBQ
    RIb2HZHn/wf038nYWJRWP1cfuTFT4pUZ84qNB2fvwPDAA8UDadU9CqqpDESisPtW
    2PZRZxH3gtZkgHbpz2PSrl+ymxalGbKPJ7ruKqlWMiWYrkAuouoI2e94MN9p2zcC
    AwEAAaNwMG4wHQYDVR0OBBYEFBN7/TAm9zLshOlKBg4YdaWnEdukMB8GA1UdIwQY
    MBaAFBN7/TAm9zLshOlKBg4YdaWnEdukMA8GA1UdEwEB/wQFMAMBAf8wGwYDVR0R
    BBQwEoIQYXV0aGVudGlrLmVxLmxhYjANBgkqhkiG9w0BAQsFAAOCAgEAfW6MW/q9
    j62xsplMndVZIHz5e/b667+V0EiMssS7/6fUcZ3a+UB65iBEVIl+gxy9eLsRmSE/
    JRhZ5Rjcx8HqLcDWrVXMtUoIwyGaqQbgsBa3iCzc8SBPnOi3mAHOp2Nqkkz3umWa
    TJoGiUKIn5TNwLI0kUTO1I/cSWQpScCGzaP3Vm6JmC/4TSPJULKVU0yYSk5hLUFt
    WevazVw5vYDyHpukLrzjrMfdBDRqWbdrbzO6eFLv+CHP7t5czxDTACl8nyhTrmVL
    C6kJdc4w8DjfuwtK46oweROTzwoA3jAW8qRQ4WSqImmJZXnKbWZ2q4zYZVpjXMNy
    ZHWxh7IK0LiLANA0LRoIqnHG4ooficWXHMWuJ+yQXM3/h9e1fC5kGUGEGf2dVL2s
    BEYt1lIo50UU3qX4kBZF/WhPi9HZYg2GlACtwI4PHqIEl0STA9Ka0IntDvTW/QdY
    56g/mjRi5WPmN1qCV1SvnR/iw+6k4AnkK6hH6gH7Ya83KTKZCJabosyyLj162+RR
    1fAFHJfuhsNB0CZ+mDUff036k2zNnHccsHZjJJvrYMsc9wRk6lvqxP29C2Q0DbE5
    5fwrxswzPb1iB1SPDXLymB8im57Pbw0vxS8ZaC56L4EshKGLtjWj5xx5nVtKQ/Go
    Ddze5yLpDP2Vh6sSRcOrtTltVuNrdGKhpLY=
    -----END CERTIFICATE-----

