---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: postgres
stringData:
  password: VMware123!VMware123!
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC7TCCAdWgAwIBAgIGAZhiYBYcMA0GCSqGSIb3DQEBCwUAMCgxFTATBgNVBAMM
    DFZNd2FyZS1EQi1DQTEPMA0GA1UECgwGVk13YXJlMB4XDTI1MDcyODIxMjUyMVoX
    DTM1MDczMTIxMjUyMVowKDEVMBMGA1UEAwwMVk13YXJlLURCLUNBMQ8wDQYDVQQK
    DAZWTXdhcmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKy+CRiMge
    xHlBa5cvxcnf1UsWjW97PKvd/35+vz4oesLXtpbl7LzDsZakovu06n3qBE6lhX0b
    +SQ9j+xq4ytSvd+YyxuDfvCqYUpU2J14iIeACu4bJQq2oIM/3z8jHTbPCRTDsYvJ
    g+uKrBXXvBNKxTRpyfByRTizDHLX8JuD3UuyykOq3VO1fjjO7MQ3Sjb/3dTMlXe+
    fFm/NdcaQK/fo9yPkrDE+7oxlkJ+EnTLsKnf7i851g2wBQxCkq1U7KjC7MnHmHoB
    EvGnPyF/riEoCdCsUqmCmKGTQodA6SFsPTJEugIZEefQ03DtHXAd3XN0aco2piGK
    MsONqQWMypUpAgMBAAGjHTAbMAsGA1UdDwQEAwIBBjAMBgNVHRMEBTADAQH/MA0G
    CSqGSIb3DQEBCwUAA4IBAQBUPGitfd+DDBwREfOptIr+YQxapR0KTMsmBVkB73gt
    rBY5wnpPeiArMqk08Th2HLw40efrRynDO4geL1IOpU5MMpwHnAW/D5NU7I7Gf/0x
    DMM6iWytJskvbX01SDv2ieUYwxxUWEaqmTu5ArF8jZZw1l8NUJxXq6jLagMFzsSC
    7EYthKugdHWia0Zn4gqAJQrbL1fKRS096ZvB6HC3ylphuVZz1jwlcGo+waEaxlGm
    6j97aMx2/v2c50OIrH7Us4hcTBRlKcRZgi5pmVXsmPJGhmcEaiLQ818fCs9p4X2o
    6KPf8mX10QHY1NUJPlx963FqMWGoHo28zYUXTKHnyzJI
    -----END CERTIFICATE-----