---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: postgres
stringData:
  password: VMware123!VMware123!
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDDDCCAfSgAwIBAgIGAZx8Hz7gMA0GCSqGSIb3DQEBCwUAMCgxFTATBgNVBAMM
    DFZNd2FyZS1EQi1DQTEPMA0GA1UECgwGVk13YXJlMB4XDTI2MDIxNzE3MzU0OFoX
    DTM2MDIyMDE3MzU0OFowKDEVMBMGA1UEAwwMVk13YXJlLURCLUNBMQ8wDQYDVQQK
    DAZWTXdhcmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCTfDjIuTms
    yK5eln0ldgN6dJuJX+IEx8ekyQZuMfXe/omNyd2tYmY04URHbVrK8q8Q4JsuhBG9
    u1rf8AkT29OK5mjzma2Xr+k4JOwundcHxHLUK1WFeJLNXgbXn4KIIDcCkyA7wyLB
    +zjbc+X2EVg29nUMwkWPXjfMTlPKhBLux/lbcYEoHrasuXSfn5wDFG+CpD+6wezA
    Vg2W+/ViZQcE4fFA5v/tsrJ3/dtZjhoinrkevFLfJ9vfTegyKgO2LCopOS+PIUeS
    xyf0z1dY2y81yzdSWnQ+2rECjfpFsLT4B8GrciehGyiRpNcoX7oYDd+fvB6bugX9
    tKzT/5Omyw/vAgMBAAGjPDA6MAsGA1UdDwQEAwIBBjAMBgNVHRMEBTADAQH/MB0G
    A1UdDgQWBBQNrkjXCw+u8AFrkmwfqt0wa3QM3DANBgkqhkiG9w0BAQsFAAOCAQEA
    LHW+AST7GiatJSjYMx+Qs3rQLXpph4BSJcd1t0QTW3ggLCQ6+JM/4gjRBQmIc1ZY
    XBW+7wB2QWG7tPn3IY7WYFWF2plwfe7hUsT83CrJzQ6KewGOuTzp/SI903UNlx1/
    ASQK87reM5TSSABsXqDGWkLKeeV3+kQtS2jb4Yb/+JT706+/G961Qd/a/McIr7nC
    rGPXDRDu1/DCLTdQ2K0FIOrVt6Ntw1iBAbvUOXz+9IUdGEMKbFgNFMd9U7Irjv3e
    sNDbGrQpyqynzEdgU3K3O6rHMrr8zyoqLocJXf8vLgQBb8ILT2e/kpYid7VHeIWr
    qq3roTVotbyafKWa9x7IfA==
    -----END CERTIFICATE-----