services:
  open-webui:
    # image: ghcr.io/open-webui/open-webui:main
    image: mn051harborrepo.uhc.com/vpaif/open-webui-gpu:25.01
    container_name: open-webui
    volumes:
      - /opt/data/open-webui:/app/backend/data
      - /opt/data/docs:/data/docs
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - WEBUI_AUTH=False
      - ENABLE_OLLAMA_API=False
      - WEBUI_NAME=${APP_NAME}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - OPENAI_API_KEY=nokey
      - WEBUI_SECRET_KEY=Sup3rS3cr3t!
      - OPEN_WEBUI_PORT=${OPEN_WEBUI_PORT}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP}
      - ENABLE_LOGIN_FORM=${ENABLE_LOGIN_FORM}
      - VECTOR_DB=${VECTOR_TYPE}
      - PGVECTOR_DB_URL=${PG_CONNECTION_STRING}
      - RAG_EMBEDDING_ENGINE=${RAG_EMBEDDING_ENGINE}
      - RAG_EMBEDDING_MODEL=${RAG_EMBEDDING_MODEL}
      - RAG_OPENAI_API_BASE_URL=${RAG_API_BASE_URL}
      - RAG_OPENAI_API_KEY=${RAG_OPENAI_API_KEY}
      - RAG_EMBEDDING_MODEL_TRUST_REMOTE_CODE=${RAG_EMBEDDING_MODEL_TRUST_REMOTE_CODE}
      - ENABLE_RAG_WEB_SEARCH=${ENABLE_RAG_WEB_SEARCH}
      - RAG_WEB_SEARCH_ENGINE=${RAG_WEB_SEARCH_ENGINE}
      - ENABLE_RAG_HYBRID_SEARCH=${ENABLE_RAG_HYBRID_SEARCH}
      - RAG_RERANKING_MODEL=${RAG_RERANKING_MODEL}
      - RAG_TEMPLATE=${RAG_TEMPLATE}
      - RAG_TOP_K=${RAG_TOP_K}
      - CHUNK_SIZE=${CHUNK_SIZE}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${EMBEDDING_MS_GPU_ID:-0}']
              capabilities: [gpu]
                  
  nemollm-embedding:
    image: nvcr.io/nim/nvidia/nv-embedqa-e5-v5-pb24h2:1.2.0
    volumes:
      - /opt/data/nv-embedqa-e5-v5:/opt/nim/.cache
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - NGC_API_KEY=${NIM_KEY}
      - HF_HOME=/opt/nim/.cache/huggingface
      - NUMBA_CACHE_DIR=/opt/nim/.cache/numba
      # - NIM_MODEL_PROFILE=edc693c6fccd68d266622eace04225421e353d7ce31e3b207afc5ff35124127b
    shm_size: 16gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${EMBEDDING_MS_GPU_ID:-0}']
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health/ready"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10m
volumes:
  webui_data:
networks:
  default:
    name: open-webui